name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}}
    strategy:
      matrix:
        otp: [22.3, 23.1]
    steps:
      - uses: actions/checkout@v2
      - uses: gleam-lang/setup-erlang@v1.1.1
        with:
          otp-version: ${{matrix.otp}}
      - name: Compile
        run: rebar3 compile
      - name: Run tests
        run: |
          rebar3 eunit -c
          rebar3 cover -v
